[package]
name = "win_sys_util"
version = "0.1.0"
authors = ["The Chromium OS Authors"]
edition = "2018"
include = ["src/**/*", "Cargo.toml"]
build = "build.rs"

[dependencies]
cfg-if = "*"
chrono = "*"
data_model = { path = "../data_model" } # provided by ebuild
libc = "*"
poll_token_derive = { version = "*", path = "../sys_util_core/poll_token_derive" }
remain = "0.2"
thiserror = "*"
serde = { version = "1", features = [ "derive", "rc" ] }
serde_json = "1"
sync = { path = "../sync" } # provided by ebuild
sys_util_core = { path = "../sys_util_core" } # provided by ebuild

[target.'cfg(windows)'.dependencies]
winapi = "*"
win_util = { path = "../win_util"}
rand = "*"

[dev-dependencies]
tempfile = "3"
regex = "*"

[build-dependencies]
cc = "1.0.25"

[features]
chromeos = []

[workspace]
