[package]
name = "swap"
version = "0.1.0"
authors = ["The Chromium OS Authors"]
edition = "2021"

[dependencies]
anyhow = "*"
base = { path = "../base" }
data_model = "*"
libc = "*"
tempfile = "*"
thiserror = "*"
userfaultfd = "0.5.0"

[patch.crates-io]
data_model = { path = "../common/data_model" }
