[package]
name = "base"
version = "0.1.0"
authors = ["The Chromium OS Authors"]
edition = "2021"

[features]
chromeos = ["sys_util/chromeos"]

[dependencies]
audio_streams = { path = "../common/audio_streams" }
data_model = { path = "../common/data_model" }
libc = "*"
remain = "0.2"
serde = { version = "1", features = [ "derive" ] }
serde_json = "*"
smallvec = "1.6.1"
sync = { path = "../common/sync" }
sys_util = { path = "../common/sys_util" }
thiserror = "1.0.20"
tempfile = "3"
base_poll_token_derive = { path = "base_poll_token_derive" }
